### ISSUE TITLE
io.appium.java_client.AppiumClientConfig and org.openqa.selenium.remote.http.ClientConfig are in unnamed module of loader 'app

### ISSUE THREAD

**Issue by yyuanmeme** [5v1988/appium-flutter-client#1]
public class FlutterTestOne {
    public static void main(String[] args) {
        AppiumDriverLocalService service = new AppiumServiceBuilder().usingAnyFreePort().build();
        service.start();
        if (service == null || !service.isRunning()) {
            throw new AppiumServerHasNotBeenStartedLocallyException(
                    "An appium server node is not started!");
        }
        BaseOptions options = new BaseOptions();
        options.setPlatformName("Android")
                .setAutomationName("Flutter")
                .setNoReset(true)
                .amend("autoGrantPermissions",true)
                .amend("appium:app", "D:\\Users\\j_yuan\\Downloads\\IBU_App_V7.85.2_09-13_15-13_Debug_FAT_18244261.apk")
                .setCapability("appPackage","ctrip.english.debug");
        try {
            AppiumFlutterDriver driver = new AppiumFlutterDriver(service.getUrl(), options);
            FlutterElement element = driver.findElement(FlutterBy.TEXT, "App 反饋");
            element.getText();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

    }
}

when I run this code,I get a error
the error is :
Exception in thread "main" java.lang.IllegalAccessError: class io.appium.java_client.AppiumClientConfig tried to access private method 'void org.openqa.selenium.remote.http.ClientConfig.<init>(java.net.URI, java.time.Duration, java.time.Duration, org.openqa.selenium.remote.http.Filter, java.net.Proxy, org.openqa.selenium.Credentials)' (io.appium.java_client.AppiumClientConfig and org.openqa.selenium.remote.http.ClientConfig are in unnamed module of loader 'app')
	at io.appium.java_client.AppiumClientConfig.<init>(AppiumClientConfig.java:62)
	at io.appium.java_client.AppiumClientConfig.defaultConfig(AppiumClientConfig.java:79)
	at io.appium.java_client.remote.AppiumCommandExecutor.<init>(AppiumCommandExecutor.java:109)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
	at io.qualityplus.flutter.driver.AppiumFlutterDriver.<init>(AppiumFlutterDriver.java:29)
	at com.example.flutterdemo.FlutterTestOne.main(FlutterTestOne.java:44)

**Comment by sw-tester** [comment]
@yyuanmeme IINM, this could be related to conflicting versions, and when you have this `appium-flutter-client`dependency in your project, you don't need to use appium java client separately as well
